name: "Trigger IFTTT Webhook Applet"
author: "hugoalh"
description: "Trigger IFTTT webhook applet."
inputs:
  eventname:
    description: "{string} Event name."
    required: true
  key:
    description: "{string} Key."
    required: true
  arbitrary:
    description: "{boolean} Trigger with an arbitrary JSON payload."
    required: false
    default: "false"
  payload:
    description: "{object} JSON payload."
    required: false
    default: "{}"
runs:
  using: "node16"
  main: "../nodejs-loader.js"
branding:
  icon: "zap"
  color: "blue"
