name: "Trigger IFTTT Webhook Applet"
author: "hugoalh"
description: "Trigger IFTTT webhook applet."
inputs:
  eventname:
    description: "{string} Event name."
    required: true
  key:
    description: "{string} Key."
    required: true
  arbitrary:
    description: "{boolean} Trigger with an arbitrary payload."
    required: false
    default: "false"
  payload:
    description: "{object} JSON/YAML/YML payload."
    required: false
    default: "{}"
runs:
  using: "docker"
  image: "docker://ghcr.io/hugoalh/trigger-ifttt-webhook-applet-ghaction:4.2.1"
branding:
  icon: "zap"
  color: "blue"
