# $<Schema>$ https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
name: "Trigger IFTTT Webhook Applet"
author: "hugoalh"
description: "Trigger IFTTT webhook applet."
inputs:
  webhook:
    description: "{string} IFTTT webhook address."
    required: false
  webhook_custompayload:
    description: "{boolean} Trigger with a standard payload or a custom payload."
    required:  false
    default: "false"
  webhook_eventname:
    description: "{string} IFTTT webhook event name."
    required: false
  webhook_key:
    description: "{string} IFTTT webhook key."
    required: false
  replaceholder_list_external:
    description: "{object} External list of the placeholder."
    required: false
    default: "{}"
  replaceholder_prefix:
    description: "{string} Prefix of the placeholder."
    required: false
    default: "%"
  replaceholder_replaceundefined:
    description: "{(boolean|null|string)} Replace undefined placeholder when placeholder is not in the list."
    required: false
    default: "false"
  replaceholder_suffix:
    description: "{string} Suffix of the placeholder."
    required: false
    default: "%"
  replaceholder_typetransform:
    description: "{boolean} Transform placeholder to the target value's type."
    required: false
    default: "true"
  value1:
    description: "{string} IFTTT default ingredient namespace `value1`."
    required: false
  value2:
    description: "{string} IFTTT default ingredient namespace `value2`."
    required: false
  value3:
    description: "{string} IFTTT default ingredient namespace `value3`."
    required: false
  payload:
    description: "{object} Custom payload."
    required: false
    default: "{}"
  dryrun:
    description: "{boolean} Dry run this action."
    required: false
    default: "false"
runs:
  using: "docker"
  image: "./use/docker/Dockerfile"
branding:
  icon: "zap"
  color: "blue"
