name: "Send To IFTTT"
author: "hugoalh"
description: "Send data to IFTTT webhook applet."
inputs:
  webhook_eventname:
    description: "{string} IFTTT webhook event name."
    required: true
  webhook_key:
    description: "{string.secret} IFTTT webhook key."
    required: true
  variable_join:
    description: "{string} Variable join if the variable list has depth."
    required: false
    default: "_"
  variable_list_external:
    description: "{object.json} External variable list that will use in the data."
    required: false
  variable_prefix:
    description: "{string} Variable prefix."
    required: false
    default: "%"
  variable_suffix:
    description: "{string} Variable suffix."
    required: false
    default: "%"
  value1:
    description: "{string} IFTTT default ingredient namespace."
    required: false
  value2:
    description: "{string} IFTTT default ingredient namespace."
    required: false
  value3:
    description: "{string} IFTTT default ingredient namespace."
    required: false
runs:
  using: "node12"
  pre: "setup.js"
  main: "main.js"
branding:
  icon: "send"
  color: "blue"
