name: "Send IFTTT Webhook"
author: "hugoalh"
description: "Send IFTTT webhook."
inputs:
  key:
    description: "{string} Key."
    required: true
  eventname:
    description: "{string} Event name."
    required: true
  arbitrary:
    description: "{boolean} Whether to send with an arbitrary payload."
    required: false
    default: "false"
  payload:
    description: "{object} JSON/YAML/YML payload."
    required: false
    default: "{}"
outputs:
  response:
    description: "{string} Response content."
  status_code:
    description: "{number} Request status code."
  status_ok:
    description: "{boolean} Whether the request was successful."
  status_text:
    description: "{string} Request status text."
runs:
  using: "node16"
  main: "dist/main.js"
branding:
  icon: "zap"
  color: "blue"
