# $<Schema>$ https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
name: "Trigger IFTTT Webhook Applet"
author: "hugoalh"
description: "Trigger IFTTT webhook applet."
inputs:
  eventname:
    description: "{string} Event name."
    required: true
  key:
    description: "{string} Key."
    required: true
  arbitrary:
    description: "{boolean} Trigger with an arbitrary JSON payload."
    required: false
    default: "false"
  payload:
    description: "{object} JSON payload."
    required: false
    default: "{}"
  dryrun:
    description: "{boolean} Dry run."
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - run: "${{github.action_path}}/../main.ps1 -arbitrary \"${{env.INPUT_ARBITRARY}}\" -dryrun \"${{env.INPUT_DRYRUN}}\" -eventName \"${{env.INPUT_EVENTNAME}}\" -key \"${{env.INPUT_KEY}}\" -payload \"${{env.INPUT_PAYLOAD}}\""
      shell: "pwsh"
branding:
  icon: "zap"
  color: "blue"
