# $<Schema>$ https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: "Test"
on:
  workflow_dispatch:
    inputs:
      webhook:
        description: "webhook"
        required: false
      replaceholder_list_external:
        description: "replaceholder_list_external"
        required: false
        default: "{}"
      value_1:
        description: "value_1"
        required: false
      value_2:
        description: "value_2"
        required: false
      value_3:
        description: "value_3"
        required: false
      webhook_eventname:
        description: "webhook_eventname"
        required: false
      webhook_key:
        description: "webhook_key"
        required: false
      value1:
        description: "value1"
        required: false
      value2:
        description: "value2"
        required: false
      value3:
        description: "value3"
        required: false
jobs:
  test:
    name: "Test"
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        use:
          - ""
          - "/use/docker"
          - "/use/nodejs"
    steps:
#       - name: "Setup NodeJS"
#         if: "${{matrix.use == '' || matrix.use == '/use/nodejs'}}"
#         uses: "actions/setup-node@v2.4.0"
#         with:
#           node-version: 14
#           registry-url: "https://registry.npmjs.org/"
      - name: "Execute"
        uses: "hugoalh/trigger-ifttt-webhook-applet-ghaction${{matrix.use}}@main"
        with:
          dryrun: true
          webhook: "${{github.event.inputs.webhook}}"
          replaceholder_list_external: "${{github.event.inputs.replaceholder_list_external}}"
          value_1: "${{github.event.inputs.value_1}}"
          value_2: "${{github.event.inputs.value_2}}"
          value_3: "${{github.event.inputs.value_3}}"
          webhook_eventname: "${{github.event.inputs.webhook_eventname}}"
          webhook_key: "${{github.event.inputs.webhook_key}}"
          value1: "${{github.event.inputs.value1}}"
          value2: "${{github.event.inputs.value2}}"
          value3: "${{github.event.inputs.value3}}"
