# $<Schema>$ https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: "Test"
on:
  workflow_dispatch:
    inputs:
      webhook:
        description: "webhook"
        required: false
      webhook_eventname:
        description: "webhook_eventname"
        required: false
      webhook_key:
        description: "webhook_key"
        required: false
      replaceholder_list_external:
        description: "replaceholder_list_external"
        required: false
        default: "{}"
      value1:
        description: "value1"
        required: false
      value2:
        description: "value2"
        required: false
      value3:
        description: "value3"
        required: false
jobs:
  default:
    name: "Default"
    runs-on: "ubuntu-latest"
    steps:
#       - name: "Setup NodeJS"
#         uses: "actions/setup-node@v2.4.0"
#         with:
#           node-version: 14
#           registry-url: "https://registry.npmjs.org/"
      - name: "Execute"
        uses: "hugoalh/trigger-ifttt-webhook-applet-ghaction@main"
        with:
          dryrun: true
          webhook: "${{github.event.inputs.webhook}}"
          webhook_eventname: "${{github.event.inputs.webhook_eventname}}"
          webhook_key: "${{github.event.inputs.webhook_key}}"
          replaceholder_list_external: "${{github.event.inputs.replaceholder_list_external}}"
          value1: "${{github.event.inputs.value1}}"
          value2: "${{github.event.inputs.value2}}"
          value3: "${{github.event.inputs.value3}}"
  docker:
    name: "Use Docker"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Execute"
        uses: "hugoalh/trigger-ifttt-webhook-applet-ghaction/use/docker@main"
        with:
          dryrun: true
          webhook: "${{github.event.inputs.webhook}}"
          webhook_eventname: "${{github.event.inputs.webhook_eventname}}"
          webhook_key: "${{github.event.inputs.webhook_key}}"
          replaceholder_list_external: "${{github.event.inputs.replaceholder_list_external}}"
          value1: "${{github.event.inputs.value1}}"
          value2: "${{github.event.inputs.value2}}"
          value3: "${{github.event.inputs.value3}}"
  nodejs:
    name: "Use NodeJS"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Setup NodeJS"
        uses: "actions/setup-node@v2.4.0"
        with:
          node-version: 14
          registry-url: "https://registry.npmjs.org/"
      - name: "Execute"
        uses: "hugoalh/trigger-ifttt-webhook-applet-ghaction/use/nodejs@main"
        with:
          dryrun: true
          webhook: "${{github.event.inputs.webhook}}"
          webhook_eventname: "${{github.event.inputs.webhook_eventname}}"
          webhook_key: "${{github.event.inputs.webhook_key}}"
          replaceholder_list_external: "${{github.event.inputs.replaceholder_list_external}}"
          value1: "${{github.event.inputs.value1}}"
          value2: "${{github.event.inputs.value2}}"
          value3: "${{github.event.inputs.value3}}"
