# $<Schema>$ https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: "Test"
on:
  workflow_dispatch:
    inputs:
      webhook:
        description: "webhook"
        required: false
      replaceholder_list_external:
        description: "replaceholder_list_external"
        required: false
        default: "{}"
      replaceholder_prefix:
        description: "replaceholder_prefix"
        required: false
        default: "%"
      replaceholder_replaceundefined:
        description: "replaceholder_replaceundefined"
        required: false
        default: "false"
      replaceholder_suffix:
        description: "replaceholder_suffix"
        required: false
        default: "%"
      replaceholder_typetransform:
        description: "replaceholder_typetransform"
        required: false
        default: "true"
      value_1:
        description: "value_1"
        required: false
      value_2:
        description: "value_2"
        required: false
      value_3:
        description: "value_3"
        required: false
      value_extra:
        description: "value_extra"
        required: false
        default: "{}"
jobs:
  test:
    name: "Test"
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        use:
          - ""
          - "/use/docker"
          - "/use/nodejs"
    steps:
#       - name: "Setup NodeJS"
#         if: "${{matrix.use == '' || matrix.use == '/use/nodejs'}}"
#         uses: "actions/setup-node@v2.4.0"
#         with:
#           node-version: 14
#           registry-url: "https://registry.npmjs.org/"
      - name: "Execute"
        uses: "hugoalh/trigger-ifttt-webhook-applet-ghaction${{matrix.use}}@main"
        with:
          dryrun: true
          webhook: "${{github.event.inputs.webhook}}"
          replaceholder_list_external: "${{github.event.inputs.replaceholder_list_external}}"
          replaceholder_prefix: "${{github.event.inputs.replaceholder_prefix}}"
          replaceholder_replaceundefined: "${{github.event.inputs.replaceholder_replaceundefined}}"
          replaceholder_suffix: "${{github.event.inputs.replaceholder_suffix}}"
          replaceholder_typetransform: "${{github.event.inputs.replaceholder_typetransform}}"
          value_1: "${{github.event.inputs.value_1}}"
          value_2: "${{github.event.inputs.value_2}}"
          value_3: "${{github.event.inputs.value_3}}"
          value_extra: "${{github.event.inputs.value_extra}}"
